# Site Settings
title: "Affiliates"
email: your@email.com
timezone: UTC
baseurl: ""  
url: "https://kaungthiha.github.io"  # Add this line with your actual username
permalink: "/:title/"

# Design
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'

# Content Settings
paginate: 30
paginate_path: /page:num/
locale: en_us
lang: en_us

# Feed Settings
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

# Build Settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed

# Analytics
ganalytics: UA-113961478-1

# Author Settings
author:
  name: Your Name
  email: your@email.com

# Social
social:
  LinkedIn: https://www.linkedin.com/in/kaungthiha/
  github: https://github.com/kaungthiha

# Plugins (supported by GitHub Pages)
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
