# Site Settings
title: "KT's Portfolio"
email: kaungthiha.3@gmail.com
timezone: UTC
baseurl: ""  
url: "https://kaungthiha.github.io"
permalink: "/:title/"

# Design
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'

# Content Settings
paginate: 30
paginate_path: /page:num/
locale: en_us
lang: en_us

# Feed Settings
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
  parse_block_html: true
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  
sass:
  sass_dir: _sass
  style: :compressed

# Analytics
ganalytics: UA-113961478-1

# Author Settings
author:
  name: Kaung Thiha
  email: kaungthiha.3@gmail.com

# Social
social:
  LinkedIn: https://www.linkedin.com/in/kaungthiha/
  github: https://github.com/kaungthiha

# Plugins (supported by GitHub Pages)
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag